# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/PMod_ESP32/PMod_ESP32.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMod_ESP32 || ORIG_REF_NAME==PMod_ESP32} -quiet] -quiet

# IP: bd/PMod_ESP32/ip/PMod_ESP32_processing_system7_0_0/PMod_ESP32_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMod_ESP32_processing_system7_0_0 || ORIG_REF_NAME==PMod_ESP32_processing_system7_0_0} -quiet] -quiet

# IP: bd/PMod_ESP32/ip/PMod_ESP32_axi_uartlite_0_0/PMod_ESP32_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMod_ESP32_axi_uartlite_0_0 || ORIG_REF_NAME==PMod_ESP32_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/PMod_ESP32/ip/PMod_ESP32_xbar_0/PMod_ESP32_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMod_ESP32_xbar_0 || ORIG_REF_NAME==PMod_ESP32_xbar_0} -quiet] -quiet

# IP: bd/PMod_ESP32/ip/PMod_ESP32_auto_pc_0/PMod_ESP32_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMod_ESP32_auto_pc_0 || ORIG_REF_NAME==PMod_ESP32_auto_pc_0} -quiet] -quiet

# IP: bd/PMod_ESP32/ip/PMod_ESP32_ps7_0_axi_periph_0/PMod_ESP32_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMod_ESP32_ps7_0_axi_periph_0 || ORIG_REF_NAME==PMod_ESP32_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PMod_ESP32/ip/PMod_ESP32_rst_ps7_0_50M_0/PMod_ESP32_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMod_ESP32_rst_ps7_0_50M_0 || ORIG_REF_NAME==PMod_ESP32_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/PMod_ESP32/ip/PMod_ESP32_xadc_wiz_0_0/PMod_ESP32_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMod_ESP32_xadc_wiz_0_0 || ORIG_REF_NAME==PMod_ESP32_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/PMod_ESP32/ip/PMod_ESP32_Top_0_0/PMod_ESP32_Top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMod_ESP32_Top_0_0 || ORIG_REF_NAME==PMod_ESP32_Top_0_0} -quiet] -quiet

# IP: bd/PMod_ESP32/ip/PMod_ESP32_axi_gpio_0_0/PMod_ESP32_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMod_ESP32_axi_gpio_0_0 || ORIG_REF_NAME==PMod_ESP32_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PMod_ESP32/ip/PMod_ESP32_axi_gpio_0_1/PMod_ESP32_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMod_ESP32_axi_gpio_0_1 || ORIG_REF_NAME==PMod_ESP32_axi_gpio_0_1} -quiet] -quiet

# XDC: c:/Vitis_SSC/Proiect_ESP32/PMod_ESP32/PMod_ESP32.gen/sources_1/bd/PMod_ESP32/PMod_ESP32_ooc.xdc
