# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Vitis_SSC/Proiect_ESP32/PMod_ESP32/PMod_ESP32.srcs/sources_1/bd/PMod_ESP32/ip/PMod_ESP32_xbar_0/PMod_ESP32_xbar_0.xci
# IP: The module: 'PMod_ESP32_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vitis_SSC/Proiect_ESP32/PMod_ESP32/PMod_ESP32.gen/sources_1/bd/PMod_ESP32/ip/PMod_ESP32_xbar_0/PMod_ESP32_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PMod_ESP32_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Vitis_SSC/Proiect_ESP32/PMod_ESP32/PMod_ESP32.srcs/sources_1/bd/PMod_ESP32/ip/PMod_ESP32_xbar_0/PMod_ESP32_xbar_0.xci
# IP: The module: 'PMod_ESP32_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vitis_SSC/Proiect_ESP32/PMod_ESP32/PMod_ESP32.gen/sources_1/bd/PMod_ESP32/ip/PMod_ESP32_xbar_0/PMod_ESP32_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PMod_ESP32_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
